### ISSUE TITLE
nats

### ISSUE THREAD

**Issue by gedw99** [machbase/neo-server#152]
on https://machbase.com/neo/tql/ is shows NATS as a TCL bridge

is this supported ?

**Comment by OutOfBedlam** [comment]
Dev planned by the end of this year.

**Comment by gedw99** [comment]
The c++ code is closed ? 

i ask only attenuation / Se iritis  reasons..

**Comment by OutOfBedlam** [comment]
I guess you are asking about engine code... machbase database engine has the different policy from machbase-neo itself.
machbase-neo is an open source but the engine is not.

**Comment by OutOfBedlam** [comment]
The NATS bridge has been merged into the main branch.
It will be released along with v8.0.20 expected in this month.

**Comment by gedw99** [comment]
@OutOfBedlam Thank you for the heads up. 

This is really useful, as I use NATS quote a lot.
