### ISSUE TITLE
Confusing license file and documentation

### ISSUE THREAD

**Issue by rambo** [machbase/neo-server#209]
LICENSE file is just a basic copyright notice, that does not actually allow anyone else to make copies of the source code even to build it, much less to modify or re-distribute.

Documentation etc talks about this being open source.

SUGGESTION: [Choose OSI approved license](https://opensource.org/licenses) that suits you and put that to LICENSE file.

Also clarify that the underlying database engine itself is not open-source and explain the licensing terms for it, especially in combination with neo-server. How free are we to use the engine with forks of neo-server for example. Note that I'm not thinking of forking the server (and even cannot before the license situation is clarified) but such extreme example is very useful in clarifying the licensing status of various components.

**Comment by OutOfBedlam** [comment]
LICENSE file has been updated.
Please refer to it.

summary is:

- commercial purpose : need to acquire commercial license.
- non-commercial (trial, study) : community license.
